upload template files
CatLecter/notification_service pull request #10
Opened 2022-05-12 19:48 UTC by CatLecter

2022-05-12 21:46 UTC, Olegt0rr requested changes

2022-05-12 21:46 UTC, Olegt0rr commented on notification/config/urls.py
> +if settings.DEBUG:
DEBUG захардкожен, его бы в настройки вынести

2022-05-13 20:07 UTC, Mlkhall reviewed
Не нашел проблем по синтаксису и стилю, по логике точно не могу выявить проблемы. Хорошая работа!

2022-05-13 20:07 UTC, Mlkhall commented on README.md
> +docker-compose up -d postgres
Очень хорошо, что с начала мы билдим постгес, хотел сам написать в чат, что предыдущая версия, не запускалась, если сначала не поднята база!

2022-05-14 11:07 UTC, merged