Html templates
CatLecter/notification_service pull request #12
Opened 2022-05-15 22:32 UTC by Mlkhall

[https://github.com/CatLecter/notification_service/projects/1#card-81807905](url)

2022-05-16 14:41 UTC, Olegt0rr requested changes

2022-05-16 14:41 UTC, Olegt0rr commented on pyproject.toml
> +pre-commit = "^2.19.0"
это надо в dev-dependencies, для прода не используется

2022-05-16 17:21 UTC, CatLecter approved these changes
OK

2022-05-17 21:11 UTC, CatLecter approved these changes

2022-05-17 21:54 UTC, closed without merging